Repository da-analysis/asac_5_dataanalysis, pull requests merged in 2024-06, with the labels that each got.

#2 [#1][Change] README File
  .github/PULL_REQUEST_TEMPLATE.md
  PR_Guide.md
  README.md
Labels: documentation

#10 [#9][Add] 텍스트 파일 업로드
  workspace/yoonjung/text.md
Labels: 윤정🐏

#12 [#8][Add] test 파일 업로드
  workspace/heesun/text.md
Labels: 희선🦥

#13 [#5][Add] test 파일 업로드 (연습용)
  workspace/text.md
Labels: 수정🔮

#15 [#3] git action 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
Labels: add
