Repository da-analysis/asac_5_dataanalysis, pull requests merged in 2024-07, with the labels that each got.

#29 [#22][Add] metadata EDA
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  README.md
  workspace/heesun/text.md
  workspace/hyewon/text.md
  workspace/seolha/[0703]data_hawai.ipynb
  workspace/seolha/[0706]metadata_EDA.ipynb
  workspace/seolha/[0710]metadata_EDA.ipynb
  workspace/seolha/metadata_EDA.py
  workspace/text.md
  workspace/yoonjung/text.md
Labels: 설하🐰

#30 [16-2] review/meta 데이터 브론즈 테이블로 생성
  workspace/soojeong/data_union.py
Labels: 수정🔮

#36 #24 아이템 간 연관규칙
  workspace/hyewon/association_rule/[연관규칙]지표 상위% 구하기.py
  workspace/hyewon/association_rule/[참고] co-count 연도-분기 연속성-ver.테스트.py
  workspace/hyewon/association_rule/[최종] 연관규칙.py
Labels: 혜원🐯, add
